import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";

const UnboundedRegular = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Veil Assets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${UnboundedRegular.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
